// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Circle

#include "./shared/Bresenham.hlsl"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float3 CirclePositionAndRadius;
float4 CircleColor;

[numthreads(1,1,1)]
void Circle (uint3 id : SV_DispatchThreadID)
{
    drawCircle(CirclePositionAndRadius.xy, CirclePositionAndRadius.z, CircleColor, Result);
}
